import Head from "next/head";
import Masthead from "../components/masthead";
import About from "../components/about";
import Contacts from "../components/contacts";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ShaleFoods</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/*nav-menu*/}
      <Masthead />
      <About />
      <Contacts />
    </div>
  );
}
